import dynamic from 'next/dynamic'
import Head from 'next/head'

export default function Home() {
  const WalletMultiButtonDynamic = dynamic(
    async () =>
      (await import('@solana/wallet-adapter-react-ui')).WalletMultiButton,
    { ssr: false }
  )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col items-center justify-center w-screen h-screen space-y-8">
          <h1 className="text-6xl font-black">Solana Dapp Starter</h1>
          <WalletMultiButtonDynamic />
        </div>
      </main>
    </>
  )
}
